spring:
  application:
    name: booking-service
  freemarker:
    enabled: false
  thymeleaf:
    cache: false

error:
  path=/error

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/

server:
  port: 0

